name = 'Hugo Theme Windy'
license = 'Apache-2.0'
licenselink = 'https://github.com/zEttOn86/hugo_theme_windy/blob/main/LICENSE'
description = 'Website based on tailwindcss'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/zEttOn86/hugo_theme_windy/tree/main'

# TODO: If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'tailwindcss', 'dark']
features = [
  'responsive',
  'dark mode',
  'table of contents',
  'json-ld',
  'katex',
  ]

# If the theme has a single author
[author]
  name = 'zEttOn86'
  homepage = 'https://zetton86.github.io/'
